### ISSUE TITLE
Checking which eye is open.

### ISSUE THREAD

**Issue by Ocareno** [AugustoEst/gazetrack#1]
Is it possible to check whether an eye is open or not? 
ie: if(left eye is open) do a thing;

Also, is there a reference online?

**Comment by AugustoEst** [comment]
The library does not allow you to check which eye is open, only if the eye data is available (i.e., any of the eyes are open). 

The Tobii SDK allows for this, so you're welcome to update the library.

**Comment by AugustoEst** [comment]
You can now do this - see the _EyePositions_ Processing demo included in the library.
