### ISSUE TITLE
punctuation problem in germany

### ISSUE THREAD

**Issue by einraum-design** [AugustoEst/gazetrack#2]
in germany windows sets ',' instead of '.' as separator in floating point numbers. 
3,141592 instead of 3.141592 
The library cannot convert the string with ',' to numbers. Could you please insert a replace ',' by '.' replacement before parsing the numbers "gazeX = Float.parseFloat(st.nextToken())  .... " or write a hint for not US users to set the number format in windows to american style.

**Comment by AugustoEst** [comment]
This shouldn't be an issue with the new library update.

**Comment by einraum-design** [comment]
thank you
