### ISSUE TITLE
Tobii Eye 4C head tracking output via UDP

### ISSUE THREAD

**Issue by cutzmf** [AugustoEst/gazetrack#4]
Hi!

Recently I've got this device and found that nothing can send data from it by UDP.

There is a thread on facetracknoir forum about phantom hope of origin UDP support.

I've found your repository and my question is in subject - Could you implement UDP sender for both gaze and head track?

**Comment by AugustoEst** [comment]
Hi,

That's definetily possible under the [Tobii SDK](https://github.com/Tobii/CoreSDK/blob/master/samples/Streams/Interaction_Streams_103/Program.cs). I just need to think of a good example of head tracking for interactive purposes in Processing.

**Comment by AugustoEst** [comment]
You can now track the user's eyes, in addition to their gaze - see the EyePositions Processing demo.

While this is not the HeadPose data stream, it still allows you to check where the user is in relation to the display (x-y-z, in both px and mm).

I'll close this now, as it is a request, and not an issue.
