### ISSUE TITLE
TobiiStream server not showing any data

### ISSUE THREAD

**Issue by dattasaurabh82** [AugustoEst/gazetrack#5]
Hi there. 
I've a Tobii 4C eye tracker. 
My windows machine is 64 Bit. 
I downloaded the suggested [TobiiStream](http://hci.soc.napier.ac.uk/GazeTrack/TobiiStream.zip) from here. 
Upon running the **TobiiStream.exe**, it doesn't show any data of tracking points. 
I assume, from the description on your site: `Before you start, make sure the TobiiStream.exe is running and displaying gaze data...` that it would be showing some data points. 
I ran it with admin privileges as well, but nothing. 

Please guide here on how to make the **TobiiStream.exe** work with my tobii. 
_Do I need to get some license, is there a config file I need to edit, Do I need some other drivers, Do I have to re-compile after that again etc. What is the troubleshooting process here basically?_
 
Your help is sincerely appreciated.

**Comment by AugustoEst** [comment]
Did you setup the Tobii hardware correctly? You can find the setup instructions here: https://help.tobii.com/hc/en-us/articles/115000432589-Is-your-Eye-Tracker-4C-not-connecting-

**Comment by dattasaurabh82** [comment]
Alright it works now after running the setup client software.
