### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Armin175** [AugustoEst/gazetrack#6]
Hi, I tried to install GazeTrack but unfortunately it does not work as expected. I installed the required library and TobiiStream.exe but when I want to start it, it just shows a white screen and nothing happens. Can you help me please? I am not so familiar with coding. I just startet a few months ago.

**Comment by AugustoEst** [comment]
When you say "when I want to start it", what do you start exactly? One of the Processing examples? Can you confirm what you see when you open TobiiStream.exe? Are you seeing rows of gaze data? 

If not, can you confirm which eye-tracker are you using, if this is installed correctly and working, and which Windows version you're on?

**Comment by Armin175** [comment]
I tried to start a library like "EyesAvailabilityAndPosition".  When I open TobiiStream.exe it says: 

"TobiiStream v2.0.4
SUCCESS: The connection to the GazeTrack Processing library has been correctly set up!
Stream Timestamp Gaze_X Gaze_Y"

That's it and nothing changes.
What do you mean by eye-tracker? I just have got my laptop camera. I have Windows 10.

**Comment by AugustoEst** [comment]
You need a Tobii eye-tracker, either the EyeX or 4C.
