### ISSUE TITLE
Initial Gaze state is "Present", even if no TobiiStream connected

### ISSUE THREAD

**Issue by oori** [AugustoEst/gazetrack#7]
Hi

Why did you choose to set the initial gazeState to `Present` ?       I would say it's supposed to be `Unknown` (or `NotPresent`), otherwise loading your library without Tobiistream wrongly gives `true` to `gazeTrack.gazePresent()` with "valid" coordinates `(0,0)`.
https://github.com/AugustoEst/gazetrack/blob/466e30e6f8ece3cd1ec4bafda5d7d23d896ea0d8/GazeTrack/src/gazetrack/TobiiStream.java#L72

I would simply change this, but I wonder why was it originally done this way (hack?).
Thanks for your library!

**Comment by AugustoEst** [comment]
Hi,

I'm afraid this is more of an oversight that an actual hack. I always start the TobiiStream first and deal with any issues there before I start Processing, so this never became a problem. I will fix this in the next version of the library, and will leave this open until then. Thanks for the heads up.
