### ISSUE TITLE
TobiiStream.exe is not working

### ISSUE THREAD

**Issue by goncagokce** [AugustoEst/gazetrack#8]
Hi,
As it is written make sure TobiiStream.exe is working, when I tried to run TobiiStream.exe it closes itself suddenly. I could be able to take screenshot as attached. Could you please help in this matter.

Many Thanks,

![TobiiStream](https://user-images.githubusercontent.com/4639633/161776958-618352b8-0180-428c-aead-2ae6c8b871ed.png)

**Comment by AugustoEst** [comment]
Hi, can you give me a bit more context? Which OS are you running, etc.?

**Comment by goncagokce** [comment]
I am running Windows 10 OS 64 bit and the eye tracker that I am using is the Tobii 4C and it is working properly.

**Comment by AugustoEst** [comment]
I wasn't able to replicate the problem on my machine running Windows 10 (version 21H1).

**Comment by oori** [comment]
I actually had the exact same issue at a customer's computer.  long story short - on Turkish windows "i386" is "ı386".
See that small difference **"ı" vs "i"**  

Maybe a Turkish IT can explain us why, but the **quickest solution** to this is to copy/rename the "i386" folder to "ı386".
